default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  host: ec2-54-227-248-123.compute-1.amazonaws.com
  port: 5432
  database: dbv2vpnng23nuo
  username: lvwuomlaxhwvnl
  password: aZWRQ8l2FBBXe-lt3-Qba_0S-u
